[package]
name = "more_hands"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["hello_bevy", "hello_world" , "my_library", "pig"]

[workspace.dependencies]
bevy = "0.16.1"
rand = { version = "0.8" }
rand_pcg = { version = "0.9.0" }
rand_xorshift = { version = "0.3.0" }
